package io.qiro.failures;

public class Retryable extends Exception {}
